//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWEB_BAI9.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_WEBSACHEntities2 : DbContext
    {
        public QL_WEBSACHEntities2()
            : base("name=QL_WEBSACHEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHITIETDONHANG> CHITIETDONHANG { get; set; }
        public DbSet<CHUDE> CHUDE { get; set; }
        public DbSet<DONHANG> DONHANG { get; set; }
        public DbSet<KHACHHANG> KHACHHANG { get; set; }
        public DbSet<NHAXUATBAN> NHAXUATBAN { get; set; }
        public DbSet<SACH> SACH { get; set; }
        public DbSet<TACGIA> TACGIA { get; set; }
        public DbSet<THAMGIA> THAMGIA { get; set; }
    }
}
