//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWEB_BAI9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public SACH()
        {
            this.CHITIETDONHANG = new HashSet<CHITIETDONHANG>();
            this.THAMGIA = new HashSet<THAMGIA>();
        }
    
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string AnhBia { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string MaChuDe { get; set; }
        public string MaNXB { get; set; }
        public Nullable<bool> Moi { get; set; }
    
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANG { get; set; }
        public virtual CHUDE CHUDE { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        public virtual ICollection<THAMGIA> THAMGIA { get; set; }
    }
}
